import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import NavBar from "./components/NavBar/NavBar";
import client from "@/lib/utils/contentful";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


async function getContentData() {
  try {
    const response = await client.getEntries({
      content_type: "homePage", // Replace with your Content Type ID
    });

    return {
      entries: response.items,
    };
  } catch (error) {
    console.error("Error fetching data from Contentful:", error);
    return {
      entries: [],
    };
  }
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const homePageData = (await getContentData()) as any;
  
  const menus = homePageData.entries[0].fields.menus;
  const pageTitle = homePageData.entries[0].fields.title;
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <NavBar menus={menus} title={pageTitle}/>
          <main className="flex p-2 justify-center">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
